server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tianfu?serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 137300
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

ip: localhost